

POST http://localhost:8000/en/dj-rest-auth/login/ HTTP/1.1
Content-Type: application/json

{"username": "test","password": "testtest"}


###
GET  http://localhost:8000/en/dj-rest-auth/logout/ HTTP/1.1
Content-Type: application/json

{{"refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY2OTM5MzA4MCwiaWF0IjoxNjY5MzA2NjgwLCJqdGkiOiI3NTY2MWMxNGIxMjc0ODljODc2MWIxOTA5YWI5YWExZCIsInVzZXJfaWQiOjJ9.zOl3hqXBDstucPQg6Gq28pmTxHaFkzCxo5uGMBBK4d4"}}


###

GET http://localhost:8000/en/login/ HTTP/1.1
Content-Type: application/json
Authorization: token  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY2OTM5MzE3NSwiaWF0IjoxNjY5MzA2Nzc1LCJqdGkiOiI0ODdlMWY2ZGFiZmU0NGQyODhiNDNhNGRjMjMyMTZiMSIsInVzZXJfaWQiOjJ9.fQLpLQk7xFgaSz6W3yeQk2fde96KFXHndJK4c0HkuIA