# Generated by Django 4.1 on 2022-09-03 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gouvernat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_gouv', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ville', models.CharField(max_length=30)),
                ('gouvernat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adresse.gouvernat')),
            ],
        ),
    ]
